#!/bin/bash
# General setup
export CONCURRENCY_LEVEL=33
export CCACHE_DISABLE=1
export MAKEOPTS="-j$(nproc)"
set -euo pipefail

# Generating CPU microcode
vendor=$(lscpu | awk '/Vendor ID/{print $3}')
if [[ "$vendor" == "GenuineIntel" ]]; then
  echo "Generating new Intel microcode cpio"
  [ -f /boot/early_ucode.cpio ] && rm /boot/early_ucode.cpio
  /usr/sbin/iucode_tool -S --write-earlyfw=/boot/early_ucode.cpio /lib/firmware/intel-ucode/*
  vendorcompile=intel
else
  echo "Generating new AMD microcode cpio"
  [ -f /boot/amd-uc.img ] && rm /boot/amd-uc.img
  echo "Generating new AMD microcode cpio"
  T=$(mktemp -d) && mkdir -p "$T/kernel/x86/microcode" && cat /lib/firmware/amd-ucode/microcode_amd*.bin >"$T/kernel/x86/microcode/AuthenticAMD.bin" && (cd "$T" && find . -type f | bsdcpio -o -H newc -R 0:0 >/boot/amd-uc.img) && rm -rf "$T" && sync
  vendorcompile=amd
fi

# If it is a new kernel version, get a copy of the current usable config
if [ ! -f /usr/src/linux/.config ]; then
  echo "Copying kernel config from current running kernel..."
  if [ -f /proc/config.gz ]; then
    zcat /proc/config.gz >/usr/src/linux/.config
  elif [ -f /etc/kernels/kernel-config-$(uname -r) ]; then
    cp /etc/kernels/kernel-config-$(uname -r) /usr/src/linux/.config
  else
    echo "No existing config found. Using defconfig."
    make defconfig
  fi
fi

# Actual kernel compilation and installation
echo "Compiling the kernel"
cd /usr/src/linux
genkernel --oldconfig --menuconfig --module-rebuild --save-config --install --microcode=$vendorcompile --bootloader=grub2 all

# Remove old kernels (keep the above one and the now penultimate)
echo "Removing old kernels from /boot"
eclean-kernel -n 2 -d
