#!/bin/bash

# Variables
LOGFILE="/tmp/clamav-$(date +'%Y-%m-%d').log";
HOST="$(hostname --long)";
EMAIL_MSG="Please see the log file attached.";
EMAIL_FROM="clamav@"$HOST"";
EMAIL_TO="marco.difresco@gmail.com";
DIRTOSCAN="/home";

# Scan the system
/usr/bin/clamscan -ri / --exclude-dir=/sys/ --exclude=backups --exclude=logs --exclude=errors > "$LOGFILE"

# Send report
if grep -rl 'Infected files: 0' $LOGFILE
then echo "No viruses fonud"
else cat $LOGFILE | mail -s "Viruses found on $HOST" $EMAIL_TO
fi
